### ISSUE TITLE
Moving a folder inside a git repo will not re-appear after :CtrlPClearAllCaches

### ISSUE THREAD

**Issue by qtrfeast** [burke/matcher#2]
Say I do `mv app/views/some-folder app/views/some-other-folder` then even after `:CtrlPClearAllCaches` and restarting vim.

I think the git config section is probably the culprit. I imagine since this change hasn't been checked in it may not be showing up.

```
let g:ctrlp_user_command = {
  \ 'types': {
    \ 1: ['.git/', 'cd %s && git ls-files'],
    \ },
  \ 'fallback': 'find %s -type f'
  \ }
```

Thought you might like to know.

**Comment by burke** [comment]
Yup, guaranteed that's the problem.

```
dummy + 0 * % git ls-files
a/file
dummy + 0 * % mv a b
dummy + 0 * D?2 % git ls-files
a/file
```

Solution is basically:
1. Commit more often
2. Use find, which will have extra junk in it unless you aggressively filter it, and will be slower
3. Deal with not being able to CtrlP to files that have been moved since the last commit.

Closing because there's really nothing I can do about this :(

EDIT: Oh, it's worth pointing out that using git is not at all necessary for matcher to work. Maybe I should add a comment to that effect in the vimrc excerpt.
